name: Containers

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  SERVER_IMAGE: ghcr.io/${{ github.repository }}/server
  WEB_IMAGE: ghcr.io/${{ github.repository }}/web

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build application containers
        run: |
          if ! docker compose build server web; then
            echo "::error ::ERR_CONTAINER_001 Failed to build application containers"
            exit 1
          fi

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish container images
        env:
          TAG: ${{ github.sha }}
        run: |
          if ! docker tag dogule-server-dev "${SERVER_IMAGE}:${TAG}"; then
            echo "::error ::ERR_CONTAINER_002 Failed to tag server image"
            exit 1
          fi
          if ! docker tag dogule-web-dev "${WEB_IMAGE}:${TAG}"; then
            echo "::error ::ERR_CONTAINER_002 Failed to tag web image"
            exit 1
          fi
          if ! docker push "${SERVER_IMAGE}:${TAG}"; then
            echo "::error ::ERR_CONTAINER_003 Failed to push server image"
            exit 1
          fi
          if ! docker push "${WEB_IMAGE}:${TAG}"; then
            echo "::error ::ERR_CONTAINER_003 Failed to push web image"
            exit 1
          fi
